services:
  radius-site:
    build:
      context: .
    image: radius-site:latest
    container_name: radius-site
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - aura-home

networks:
  aura-home:
    external: true
    name: aura-home_default
